name: Build and deploy Vite React app to Azure Web App - student-planner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # 🔐 Login to Azure (REQUIRED)
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2E30D07C90654F418DC4F7F0EB941DF6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AA06CCDCAA3F45B68DA605D1EF031DC8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_46D6B98B11974AB29E13741CB7DAD6A2 }}

      # 🚀 Deploy ONLY dist folder
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'student-planner'
          slot-name: 'Production'
          package: dist
